### ISSUE TITLE
Reading then writing the same thing causes archive corruption

### ISSUE THREAD

**Issue by mattangus** [Neodymium146/gta-toolkit#3]
I am trying to load in an archive file, then save it without modification. Either I'm not using the API properly, or there is a bug.

Here is the code that I have for loading and then directly saving the archive again.
```
RageLib.GTA5.ArchiveWrappers.RageArchiveWrapper7 root = ResourceLoader.GetRoot(archivePath);
RageLib.Archives.IArchiveFile textureFile = ResourceLoader.LoadResource(root, testPath);
MemoryStream textureFileStream = new MemoryStream();
textureFile.Export(textureFileStream);

//load into wrapper
var dictWrapper = new RageLib.ResourceWrappers.GTA5.PC.Textures.TextureDictionaryFileWrapper_GTA5_pc();
dictWrapper.Load(textureFileStream);

//save back to stream
MemoryStream ms = new MemoryStream();
dictWrapper.Save(ms);
textureFile.Import(ms);
root.Flush();
```
The `ResourceLoader.LoadResource` function just goes through the directory structure based on the path provided.

This code will run successfully the first time, but when I try and open the archive again there is an error loading the information.

```
Unhandled Exception: System.Exception: Error in RPF7 file entry.
   at RageLib.GTA5.Archives.RageArchiveBinaryFile7.Read(DataReader reader) in gta-toolkit\RageLib.GTA5\Archives\RageArchive7.cs:line 468
   at RageLib.GTA5.Archives.RageArchive7.ReadHeader(Byte[] aesKey, Byte[] ngKey) in gta-toolkit\RageLib.GTA5\Archives\RageArchive7.cs:line 157
   at RageLib.GTA5.ArchiveWrappers.RageArchiveWrapper7.Open(Stream stream, String fileName, Boolean leaveOpen) in gta-toolkit\RageLib.GTA5\ArchiveWrappers\RageArchiveWrapper7.cs:line 399
   at RageLib.GTA5.ArchiveWrappers.RageArchiveDirectoryWrapper7.GetArchive(String name) in gta-toolkit\RageLib.GTA5\ArchiveWrappers\RageArchiveWrapper7.cs:line 518
```

**Comment by Neodymium146** [comment]
I just fixed 2 problems:
- Texture dictionary wrapper was broken and therefore writing texture files using the wrapper classes was not possible.
- Importing binary and resource files into archives was performed from the current stream position instead of position 0. So it was necessary to set the position to 0 with ms.Position=0 before importing.

However, I was not able to reproduce exactly your problem with "Error in RPF7 file entry". So let me know if the problem still exists with the updated code.
